#!/usr/bin/env python3
"""
build_digest.py — render an items.json bundle into an HTML email digest.

Deterministic. Reads the bundle written by fetch_videos.py. If an item has a
"summary" field (added by Claude during the routine), it is shown; otherwise a
trimmed description is used as a fallback so the digest is still useful without
a summarisation pass.

Usage:
    python3 build_digest.py /tmp/yt-newsletter/items.json \
        --out /tmp/yt-newsletter/digest.html --title "YouTube Digest"
"""
from __future__ import annotations

import argparse
import datetime as dt
import html
import json
import sys
from pathlib import Path


def fmt_duration(seconds) -> str:
    if not seconds:
        return ""
    seconds = int(seconds)
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f"{h}:{m:02d}:{s:02d}" if h else f"{m}:{s:02d}"


def fmt_published(iso: str) -> str:
    try:
        d = dt.datetime.fromisoformat(iso.replace("Z", "+00:00"))
        return d.strftime("%b %-d, %Y")
    except Exception:  # noqa: BLE001
        return iso[:10]


def fmt_views(n) -> str:
    if not n:
        return ""
    n = int(n)
    if n >= 1_000_000:
        return f"{n/1_000_000:.1f}M views"
    if n >= 1_000:
        return f"{n/1_000:.0f}K views"
    return f"{n} views"


def item_blurb(item: dict, max_chars: int = 600) -> str:
    """Summary if present, else a trimmed description."""
    text = (item.get("summary") or "").strip()
    if not text:
        text = (item.get("description") or "").strip()
        if len(text) > max_chars:
            text = text[:max_chars].rsplit(" ", 1)[0] + "…"
    return text


def render(bundle: dict, title: str) -> str:
    items = bundle.get("items", [])
    today = dt.datetime.now(dt.timezone.utc).strftime("%A, %B %-d, %Y")
    cards = []
    for it in items:
        thumb = html.escape(it.get("thumbnail") or "")
        url = html.escape(it.get("url") or "#")
        vtitle = html.escape(it.get("title") or "(untitled)")
        channel = html.escape(it.get("channel") or "")
        meta_bits = [b for b in (
            channel,
            fmt_published(it.get("published", "")),
            fmt_duration(it.get("duration")),
            fmt_views(it.get("view_count")),
        ) if b]
        meta_line = html.escape(" · ".join(meta_bits))
        blurb = html.escape(item_blurb(it)).replace("\n", "<br>")
        no_tx = "" if it.get("transcript") else (
            '<div style="font-size:11px;color:#b00;margin-top:6px">'
            '⚠ summarised from description only (no transcript)</div>')
        thumb_html = (
            f'<a href="{url}"><img src="{thumb}" width="160" '
            f'style="display:block;border-radius:8px;border:0" alt=""></a>'
            if thumb else "")
        cards.append(f"""
        <tr>
          <td style="padding:16px 0;border-bottom:1px solid #eee;vertical-align:top">
            <table role="presentation" cellpadding="0" cellspacing="0" width="100%">
              <tr>
                <td width="176" style="vertical-align:top;padding-right:16px">{thumb_html}</td>
                <td style="vertical-align:top">
                  <a href="{url}" style="font-size:17px;font-weight:600;color:#0b57d0;text-decoration:none">{vtitle}</a>
                  <div style="font-size:13px;color:#666;margin:4px 0 8px">{meta_line}</div>
                  <div style="font-size:14px;color:#222;line-height:1.5">{blurb}</div>
                  {no_tx}
                </td>
              </tr>
            </table>
          </td>
        </tr>""")

    body = "".join(cards) if cards else (
        '<tr><td style="padding:24px 0;color:#666">No new videos since the '
        'last digest.</td></tr>')

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title></head>
<body style="margin:0;background:#f6f7f9;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f6f7f9;padding:24px 0">
    <tr><td align="center">
      <table role="presentation" width="640" cellpadding="0" cellspacing="0" style="max-width:640px;background:#fff;border-radius:12px;padding:28px 32px">
        <tr><td style="padding-bottom:8px">
          <div style="font-size:22px;font-weight:700;color:#111">📺 {html.escape(title)}</div>
          <div style="font-size:13px;color:#888;margin-top:4px">{today} · {len(items)} new video{'s' if len(items)!=1 else ''}</div>
        </td></tr>
        <tr><td><table role="presentation" width="100%" cellpadding="0" cellspacing="0">{body}</table></td></tr>
        <tr><td style="padding-top:20px;font-size:11px;color:#aaa;text-align:center">
          Generated by yt-newsletter · cutoff {html.escape(bundle.get('cutoff','')[:10])}
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>"""


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("items", type=Path, help="items.json from fetch_videos.py")
    ap.add_argument("--out", type=Path, default=Path("/tmp/yt-newsletter/digest.html"))
    ap.add_argument("--title", default="YouTube Digest")
    args = ap.parse_args(argv)

    if not args.items.exists():
        print(f"[error] items file not found: {args.items}", file=sys.stderr)
        return 2
    bundle = json.loads(args.items.read_text(encoding="utf-8"))
    out_html = render(bundle, args.title)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(out_html, encoding="utf-8")
    print(f"[done] wrote digest ({len(bundle.get('items', []))} items) to {args.out}",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
